version: "3.9"

services:
  my-portfolio-app:
    image: gyarsilalsolanki011/my-portfolio-app:latest
    container_name: portfolio-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - portfolio-network

networks:
    portfolio-network:
        driver: bridge