version: "3.9"

services:
  portfolio-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio-app:latest
    container_name: portfolio-container
    ports:
      - "8080:8080"
    env_file:
      - .env

